const ContainerDataTypes = {
  SET_IMG_START: 'SET_IMG_START',
  SET_IMG_SUCCESS: 'SET_IMG_SUCCESS',
  SET_IMG_FAILURE: 'SET_IMG_FAILURE',

  UPDATE_IMG_START: 'UPDATE_IMG_START',
  UPDATE_IMG_SUCCESS: 'UPDATE_IMG_SUCCESS',
  UPDATE_IMG_FAILURE: 'UPDATE_IMG_FAILURE',
};

export default ContainerDataTypes;
